### ISSUE TITLE
Usability of this fork

### ISSUE THREAD

**Issue by Mayeu** [JavaJens/TextSecure#10]
Hi,

I have a question about the usability of this fork, do you use it daily? I see that the commit diff is really short (the websocket-reborn branch), so I suppose it is a pretty stable feature. Is it usable for a user that is capable of compiling new version regularly?

(I am stuck with a pretty old version I have compiled myself to ensure I have SMS support, but I really want to upgrade to a new one)

**Comment by JavaJens** [comment]
No, this is not a stable fork :D But feel free to test and report back.
Also the server against which this is run, is a development server (textsecure-service-staging).

If you want I can provide a patch that allows you to easily install two versions in parallel.

**Comment by jomo** [comment]
I would like to test this myself and I have a few questions, too:
1. Are the Google dependencies already removed?
2. Is there a public development server or do I need to set that up myself, too?
3. Can servers communicate under each other (so I can message others that use the default TS server)?

---

Thanks for all the effort you put into websocket support :+1:

**Comment by JavaJens** [comment]
1. You need Google services to built, but not on your phone.
   2+3. It uses the Whispersystems Staging Server, but afaik it is not federated.

**Comment by dev-mb-zz** [comment]
How can I change the Staging server into a federated one to be able to communicate with "normale" gcm-users? Anything else to do before compiling to test under normal conditions with users which use text secure from the Google play store?

**Comment by JavaJens** [comment]
You should look into the Release.java file.
For the rest see the Readme in the websocket-reborn branch
