### ISSUE TITLE
Retrieving messages does not work

### ISSUE THREAD

**Issue by haffenloher** [JavaJens/TextSecure#11]
Hi!
When testing your websocket-reborn branch (including your forked libtextsecure), I wasn't able to receive any messages.
There was not much Textsecure-related log output, except this:

```
03-05 15:16:48.843 W/MessageRetrievalService(31143): Active Count: 1
03-05 15:16:48.861 W/MessageRetrievalService(31143): Network requirement: true
03-05 15:16:48.861 W/MessageRetrievalService(31143): Active Count: 0
03-05 15:16:48.864 W/MessageRetrievalService(31143): Network requirement: true
03-05 15:16:48.930 W/MessageRetrievalService(31143): Active Count: 1
03-05 15:16:48.932 W/MessageRetrievalService(31143): Network requirement: true
03-05 15:16:51.073 W/MessageRetrievalService(31143): Active Count: 0
etc.
```

Is there anything I can do to help you debug this issue?

**Comment by pejakm** [comment]
If you used testing server you cannot receive messages sent from production builds of TextSecure.

**Comment by haffenloher** [comment]
Of course, sorry for being unclear. The sending client is registered to the same server.

**Comment by JavaJens** [comment]
Very strange. Don't you have any other useful output?
I would expect at least the following:

```
Waiting for websocket state change....
Making websocket connection....
Reading message...
...
```

The repetitive log off the active count means that an activity registers and deregisters with the service frequently, the only activities that do this, afaik, are PassphraseRequiredActionBarActivity and PassphraseRequiredSherlockListActivity.

I don't have a passphrase setup, but will do that and try to reproduce the error.

Edit:
I can't reproduce this. Both unlocked and locked....
 As an FYI: after a restart of your device, you have to launch TextSecure once as I haven't set up a boot listener yet...

**Comment by haffenloher** [comment]
My fault, I'm sorry - I didn't realise I had to reregister, so I tested your branch used an existing account. After reading through your changes to the registration process, I made a new account, everything works now.
