### ISSUE TITLE
Force close when sending image.

### ISSUE THREAD

**Issue by jensMF** [JavaJens/TextSecure#14]
The actual version force closes if I hit the send button for a picture. Whe I restart the app it sends the picture without a problem. I do not need to hit the send button again.

**Comment by relyt29** [comment]
is there anything useful in the logcat debug logs when the app crashes? Plug in your phone to your computer, do adb logcat on the command line and crash the app

Also you are aware that this version is a crapton of commits behind master at this point so it may have been a bug fixed upstream

**Comment by jensMF** [comment]
I don't know whether the logcat is helpful but it is too long to post. What can I look for? What filter could I use?

**Comment by jensMF** [comment]
Yes I know its behind master and was hoping for an update…

**Comment by relyt29** [comment]
look through the logcat for "org.thoughtcrime.securesms"

**Comment by JavaJens** [comment]
Sorry I didn't reply sooner. You can upload crash logs as gists for example.
But I am closing this issue as the branch was so outdated. I will push an update soon and if the problem persists, feel free to re-open with a crash log.
