### ISSUE TITLE
Redphone

### ISSUE THREAD

**Issue by ghost** [JavaJens/TextSecure#31]
I know this has nothing to do with Textsecure, 
But I'd like to know if we could do the same for redphone. I'm not sure if redphone is GCM or Google framework dependent though.
Because I'd very much like to see it on F-Droid aswell :)

**Comment by paride** [comment]
RedPhone will probably be merged with TextSecure "soon". It is probably better to concentrate the efforts on TextSecure and wait for the merge...

**Comment by ghost** [comment]
@legovini If that's the case we should indeed focus on textsecure.

Also, does anybody know if this is going to remain a fork of TS or will all of this eventually be merged upstream?

**Comment by JavaJens** [comment]
The core idea is of course to merge this with upstream. But for that we believe to have to gather some more statistics regarding battery consumption first 

Feel free to help out :smile:

**Comment by patcon** [comment]
@JasperWeiss OWS seems amenable, but a quick look over the websocket branch makes me think some clean-up and re-org still needs to happen before it would be allowed to be merged. (Sorry to be vague, but it _is_ on my todo list to grapple with the TS codebase and make concrete suggestions. Or perhaps my sense is wrong, and it's all perfect as-is :)

**Comment by ghost** [comment]
I'd like to help out with the battery statistics.
I'm running CM 12.1 on a HTC one M8
I'll wipe it, test it with websocket
wipe it, add gapps, and try the official gcm
If someone could point me to a .apk for the websocket version because I'm not sure how to compile it from source.

**Comment by relyt29** [comment]
This should be closed.

Future discussions of this nature should probably go on a mailing list like whispersystems-community-unofficial@googlegroups.com (if @patcon is okay with widening the topic to all unsupported TS development instead of just the server configs) but in general we should be treating this like the issue tracker its supposed to be not a discussion forum. Otherwise it becomes hard for devs to stay organized. (E.g. upstream)

**Comment by patcon** [comment]
Meh, I'm ok with using it for anything relevant that doesn't fit on the main mailing list. I'm not sure that this convo would be unwelcome on the main one, but everyone can try to use their best judgement on that :)
