### ISSUE TITLE
Remove TextSecure & WhisperSystems branding

### ISSUE THREAD

**Issue by patcon** [JavaJens/TextSecure#33]
If someone is hosting the app in an f-droid repo, this should probably be done. (?)

fwiw I'm not particularly in favour of this fork, but starting a new issue in light of this comment, and to keep issues granular:
https://github.com/JavaJens/TextSecure/issues/32#issuecomment-138094274

**Comment by Isgar** [comment]
I am in favor of this, as at this point it doesn't seem likely to be merged upstream anytime soon.
I get the point that this is causing confusion, so changing the name and logo and calling it a 'third party client for TextSecure' is appropriate.

The alternative is not distributing any binaries. Would a notice, that you are violating trademarks by doing so, be sufficient?

**Comment by xmikos** [comment]
I am not going to stop distributing binaries in my https://fdroid.eutopia.cz repository. But like I have written to Moxie on Twitter, I am willing to rename WebSocket-fork build to something else (I will not rename builds from unchanged official TextSecure sources, that would be crazy).

Any suggestions on new name? WebSocketSecure seems too long, but I am still hoping that Moxie some day in the future will become reasonable and merge WebSocket support into official TextSecure client (so I am looking at this like on temporary name... but maybe I am too naive ;-)).

**Comment by paride** [comment]
Call it Signal: the is no such Android app!
Just kidding, I hope this will be solved in a friendly way.

Unfortunately I don't think Moxie is going to merge WebSocket support into the official clients any soon. Sometimes I even think that the "we're working on it" notice on their website is a subtle way to discourage forks without actually implementing it.

In looking for a new name keep in mind that it may come a day when TextSecure and RedPhone will finally get merged, so a name like TextSomething might not be very appropriate.

What about Shannon (after Claude Shannon)?

**Comment by schachmat** [comment]
Why do you think it is not going to be merged? There was only one pull-request until now and at the time it was not ready.

Now the changes are rather minimal and easy to check. The only concern (from my understanding) are the power issues #22.

So please focus your time on real development instead of splitting the community.

**Comment by xmikos** [comment]
Moxie started with legal threats (yesterday on Twitter), so I am going to rename my builds. He doesn't have trademark registered in EU (at least I didn't find it), but he seems to hate the idea of independent builds (even from unchanged source code) so much that maybe he is capable of registering it just because of that. And of course I don't want him to waste time and money like that.

I will keep same appid, only strings will be renamed, so if you are using my builds from https://fdroid.eutopia.cz, you will not loose app data. The names I have chosen for my renamed builds are **TextLibre** and **PhoneLibre**.

**Comment by xmikos** [comment]
And it's done, renamed builds are uploaded now.

**Comment by paride** [comment]
@xmikos It seems to me that RedPhone finally got merged into TextSecure in the master branch, and that TextSecure has been renamed into Signal. The release is probably imminent.

I'm writing this here as you may want to rename TextLibre too.

**Comment by xmikos** [comment]
@legovini I know, I am watching commits on TextSecure. I will do renamed release of Signal soon after official release.

**Comment by xmikos** [comment]
I have now published independent build of latest Signal 3.0.1 on https://fdroid.eutopia.cz. It has been renamed to **LibreSignal**.

**Comment by xmikos** [comment]
FYI: I have noticed that `android:allowBackup="false"` has been added to Signal AndroidManifest.xml file. So people now can't backup Signal without rooting their device.

**Comment by patcon** [comment]
> I have noticed that android:allowBackup="false" has been added to Signal AndroidManifest.xml file. So people now can't backup Signal without rooting their device.

It might have something to do with disabling the new auto-backup features for app data :)
https://developer.android.com/training/backup/autosyncapi.html#disabling

**Comment by xmikos** [comment]
@patcon Whatever is the reason, disallowing backups without first (re)implementing encrypted export of keys is really rude to users. Without root, nobody can now e.g. switch to another device without losing keys (which means users have to compare all fingerprints with everybody else again to rule out MITM, not a small task).

**Comment by xmikos** [comment]
@patcon autobackup feature is only relevant to Android 6, which only very few users have on their devices (and it will take very long time before it will hit significant percent of users). And if you have strong password, it doesn't affect security of TextSecure/Signal. Disallowing backups on the other hand affects almost everyone.

**Comment by patcon** [comment]
I'm with you that it sucks :( Maybe open an issue in the upstream repo?

**Comment by relyt29** [comment]
Comment on the mailing list. Opening issues for philosophical disagreements almost always gets closed with "This is an issue tracker not a discussion forum"

**Comment by dejIO** [comment]
@xmikos Your move has been received very favourably by renowed German tech blogger Mike Kuketz: http://www.kuketz-blog.de/android-signal-ohne-google-cloud-messaging/

Congratulations!
