### ISSUE TITLE
Merge upstream 2.28.0 into websocket-reborn + Signal update

### ISSUE THREAD

**Issue by relyt29** [JavaJens/TextSecure#37]
Folks,

Again still too busy to do this right now, but upstream has had a major update. If someone wants to step in again to do the merge from upstream, go for it otherwise in a few weeks I will finally get back to it.

If someone does step in to do the merge, BE CAREFUL, MANUALLY TEST THE NEW CODE WORKS - there's gonna be a huge diff and stuff will probably break because of it.

**Comment by relyt29** [comment]
Nevermind I am actually working on this, I have the code merged and apks generated. Will do testing later. I'm unsure how to handle the redphone components... Presumably there's a new "voice" boolean that gets sent to the server upon registration, I may set that to false until calling can be figured out without GCM

**Comment by schachmat** [comment]
Actually I can at least initiate calls with the original redphone without GCM, so I don't think there is a hard dependency there.

**Comment by relyt29** [comment]
ooh that gives me hope, I'll look into it more when I get a chance to load up the APKs onto my test phones
