### ISSUE TITLE
Network failure when calling with websocket-reborn

### ISSUE THREAD

**Issue by vuyibiran** [JavaJens/TextSecure#41]
Hello

First of all: Your work (I mean all the contributors) is really appreciated. The websockets is really nice if one does not want to rely on google ;)
Thanks for the effort and pls keep up the good work. Maybe this will eventually integrated to the original.

To the problem:
I built your fork today from source and tried to make a call between two websocket-reborn versions (3.0.1-dev).
But I got the error about a network failure:

> W/SignalingSocket( 6132): Connected to: 52.1.187.175
> D/QC-QMI  (  202):  Calling cooked async Callback 
> D/QC-QMI  (  202):  Inside qmi_client_decode_msg_async  Callback 
> D/CellBroadcastConfigService( 3602): enabled emergency cell broadcast channels
> D/CellBroadcastConfigService( 3602): disabling cell broadcast channel 50
> D/IccSmsInterfaceManager( 2748): [IccSmsInterfaceManager] Failed to remove GSM cell broadcast subscription for MID range 50 to 50 from client com.android.cellbroadcastreceiver
> D/CellBroadcastConfigService( 3602): disabling channels 919-928
> D/IccSmsInterfaceManager( 2748): [IccSmsInterfaceManager] Failed to remove GSM cell broadcast subscription for MID range 919 to 928 from client com.android.cellbroadcastreceiver
> D/CellBroadcastConfigService( 3602): disabling cell broadcast ETWS test messages
> D/IccSmsInterfaceManager( 2748): [IccSmsInterfaceManager] Failed to remove GSM cell broadcast subscription for MID range 4355 to 4355 from client com.android.cellbroadcastreceiver
> D/CellBroadcastConfigService( 3602): disabling cell broadcast CMAS test messages
> D/IccSmsInterfaceManager( 2748): [IccSmsInterfaceManager] Failed to remove GSM cell broadcast subscription for MID range 4380 to 4382 from client com.android.cellbroadcastreceiver
> D/IccSmsInterfaceManager( 2748): [IccSmsInterfaceManager] Failed to remove cdma broadcast subscription for MID range 4100 to 4100 from client com.android.cellbroadcastreceiver
> W/PhoneNumberFormatter( 6132): Got local CC: DE
> D/SignalingSocket( 6132): Sending signal...
> W/LineReader( 6132): Chomped line: 48 54 54 50 2f 31 2e 30 20 34 30 33 20 45 72 72 6f 72 
> W/LineReader( 6132): Buffer length: 22
> W/LineReader( 6132): Writing remaining to buffer, offset: 20 Length: 2
> W/LineReader( 6132): Chomped line: 
> W/LineReader( 6132): Buffer length: 2
> W/InitiatingCallManager( 6132): org.thoughtcrime.redphone.signaling.SignalingException: Unknown response: 403
> W/InitiatingCallManager( 6132):     at org.thoughtcrime.redphone.signaling.SignalingSocket.initiateConnection(SignalingSocket.java:187)
> W/InitiatingCallManager( 6132):     at org.thoughtcrime.redphone.call.InitiatingCallManager.run(InitiatingCallManager.java:77)
> D/NuPlayerDriver(  204): reset(0xb830a6e0)
> D/NuPlayerDriver(  204): notifyResetComplete(0xb830a6e0)
> E/MediaPlayer-JNI( 6132): QCMediaPlayer mediaplayer NOT present
> W/RedPhone( 6132): Got message from service: 2
> W/RedPhoneService( 6132): termination stack
> W/RedPhoneService( 6132): java.lang.Exception
> W/RedPhoneService( 6132):   at org.thoughtcrime.redphone.RedPhoneService.terminate(RedPhoneService.java:340)
> W/RedPhoneService( 6132):   at org.thoughtcrime.redphone.RedPhoneService.notifyServerFailure(RedPhoneService.java:467)
> W/RedPhoneService( 6132):   at org.thoughtcrime.redphone.call.InitiatingCallManager.run(InitiatingCallManager.java:106)
> D/LockManager( 6132): Entered Lock State: PARTIAL
> D/AccelerometerListener( 6132): enable(false)
> D/org.thoughtcrime.redphone.audio.IncomingRinger( 6132): Cancelling vibrator
> E/MediaPlayer( 6132): stop called in state 4
> E/MediaPlayer( 6132): error (-38, 0)
> E/MediaPlayer( 6132): Error (-38,0)
> D/WifiService(  644): releaseWifiLockLocked: WifiLock{RedPhone Wifi type=3 binder=android.os.BinderProxy@2a49ecea}
> D/LockManager( 6132): Entered Lock State: SLEEP
> D/AccelerometerListener( 6132): enable(false)
> I/FFmpegExtractor(  204): android-source:0xb8184350
> I/FFMPEG  (  204): [mp3 @ 0xb81f1bd0] Skipping 0 bytes of junk at 0.
> I/FFMPEG  (  204): [mp3 @ 0xb81f1bd0] Estimating duration from bitrate, this may be inaccurate
> I/FFMPEG  (  204): Input #0, mp3, from 'android-source:0xb8184350':
> I/FFMPEG  (  204):   Duration: 00:00:00.50, start: 0.000000, bitrate: 127 kb/s
> I/FFMPEG  (  204):     Stream #0:0: Audio: mp3, 22050 Hz, mono, s16p, 128 kb/s
> D/FFmpegExtractor(  204): FFmpegExtrator, url: android-source:0xb8184350, format_name: mp3, format_long_name: MP2/3 (MPEG audio layer 2/3)
> D/FFmpegExtractor(  204): suppoted codec(mp3) by official Stagefright
> D/FFmpegExtractor(  204): ffmpeg detected media content as 'audio/mpeg' with confidence 0.08
> D/ExtendedUtils(  204): extended extractor not needed, return default
> E/MediaPlayer( 6132): Should have subtitle controller already set
> D/NuPlayerDriver(  204): start(0xb830a6e0)
> I/GenericSource(  204): start
> W/Utils   (  204): bool android::canOffloadStream(const android::spandroid::MetaData&, bool, const android::spandroid::MetaData&, bool, audio_stream_type_t) No sample bit depth info in meta data
> I/ExtendedUtils(  204): No channel mask, try channel count
> I/NuPlayer(  204): Could not offload audio decode, pcm offload decided :0
> W/Utils   (  204): bool android::canOffloadStream(const android::spandroid::MetaData&, bool, const android::spandroid::MetaData&, bool, audio_stream_type_t) No sample bit depth info in meta data
> I/ACodec  (  204): sampleRate=22050 channels=1 bits=16
> D/ALSAStreamOps(  204): setParameters(): keyRouting with device 0x1
> D/ALSAStreamOps(  204): setParameters(): keyRouting with device 0x1
> D/ALSADevice(  204): route: devices 0x1 in mode 0
> D/ALSADevice(  204): No valid input device: 0
> D/alsa_ucm(  204): snd_use_case_set(): uc_mgr 0xb8156830 identifier _enadev value Earpiece
> D/alsa_ucm(  204): Set mixer controls for HiFi enable 1
> D/alsa_ucm(  204): Setting mixer control: SLIMBUS_0_RX Audio Mixer MultiMedia1, value: 1
> D/ALSADevice(  204): switchDevice: mCurTxUCMDevivce None mCurRxDevDevice Earpiece
> D/ALSAStreamOps(  204): setParameters(): keyRouting with device 0x1
> D/ALSAStreamOps(  204): setParameters(): keyRouting with device 0x1
> D/ALSADevice(  204): route: devices 0x1 in mode 0
> D/ALSADevice(  204): No valid input device: 0
> D/alsa_ucm(  204): snd_use_case_set(): uc_mgr 0xb8156830 identifier _enadev value Earpiece
> D/alsa_ucm(  204): Set mixer controls for HiFi enable 1
> D/alsa_ucm(  204): Setting mixer control: SLIMBUS_0_RX Audio Mixer MultiMedia1, value: 1
> D/ALSADevice(  204): switchDevice: mCurTxUCMDevivce None mCurRxDevDevice Earpiece
> E/AudioTrack(  204): AudioTrack::set : Exit
> D/ALSAStreamOps(  204): setParameters(): keyRouting with device 0x1
> D/ALSAStreamOps(  204): setParameters(): keyRouting with device 0x1
> D/ALSADevice(  204): route: devices 0x1 in mode 0
> D/ALSADevice(  204): No valid input device: 0
> D/alsa_ucm(  204): snd_use_case_set(): uc_mgr 0xb8156830 identifier _enadev value Earpiece
> D/alsa_ucm(  204): Set mixer controls for HiFi enable 1
> D/alsa_ucm(  204): Setting mixer control: SLIMBUS_0_RX Audio Mixer MultiMedia1, value: 1
> D/ALSADevice(  204): switchDevice: mCurTxUCMDevivce None mCurRxDevDevice Earpiece
> D/ALSAStreamOps(  204): setParameters(): keyRouting with device 0x1
> D/ALSAStreamOps(  204): setParameters(): keyRouting with device 0x1
> D/ALSADevice(  204): route: devices 0x1 in mode 0
> D/ALSADevice(  204): No valid input device: 0
> D/alsa_ucm(  204): snd_use_case_set(): uc_mgr 0xb8156830 identifier _enadev value Earpiece
> D/alsa_ucm(  204): Set mixer controls for HiFi enable 1
> D/alsa_ucm(  204): Setting mixer control: SLIMBUS_0_RX Audio Mixer MultiMedia1, value: 1
> D/ALSADevice(  204): switchDevice: mCurTxUCMDevivce None mCurRxDevDevice Earpiece

**Comment by relyt29** [comment]
Yes, phone calls are not supported at this time on websocket-reborn. We hope to have them supported in the future, but for now they are not supported.
