### ISSUE TITLE
Websocket-reborn 3.0.1-dev cannot communicate with signal 3.0.2

### ISSUE THREAD

**Issue by vuyibiran** [JavaJens/TextSecure#42]
I remember that it was possible to communicate between websocket-reborn 2.27 and textsecure 2.27.

I tried today to send some text from websocket-reborn 3.0.1-dev to signal 3.0.2 (on android) but the text never arrives. This also does not work vice versa.

Unfortunately I cannot attach a useful log.

**Comment by relyt29** [comment]
The changes between 3.0.1 and 3,0.2 are minimal, I highly doubt that 3.0.2 is the/a root of the problem. It's possible, likely even, that there are issues with the websocket-reborn 3.0.1 implementation. But with only anecdotal evidence of problems, and no debug information, I can't really help. If anybody else is experiencing the same problem, please comment further...

if you have the android debugging bridge installed on your computer, you can take a log of what's going with `adb logcat`

**Comment by vuyibiran** [comment]
I can provide a log.
I think this could be some problem server side.
But I hope you can find something, so here is the log:
.

> --------- beginning of main
> W/ConversationActivity( 4543): isManual Selection: false
> W/ConversationActivity( 4543): forceSms: false
> I/LatinIME( 2305): Starting input. Cursor position = 3,3
> W/MmsSmsDatabase( 4543): Executing query: SELECT _id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (thread_id = 2) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (thread_id = 2) ORDER BY date_received DESC) LIMIT 1
> W/MmsSmsDatabase( 4543): Executing query: SELECT _id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (thread_id = 2) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (thread_id = 2) ORDER BY date_received DESC)
> W/MessageDatabase( 4543): Updating ID: 4 to base type: 22
> W/MmsSmsDatabase( 4543): Executing query: SELECT _id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (thread_id = 2) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (thread_id = 2) ORDER BY date_received DESC) LIMIT 1
> W/MessageDatabase( 4543): Updating ID: 4 to base type: 2097152
> W/MmsSmsDatabase( 4543): Executing query: SELECT _id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (thread_id = 2) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (thread_id = 2) ORDER BY date_received DESC) LIMIT 1
> W/PushTextSendJob( 4543): Sending message: 4
> W/TextSecureMessageSender( 4543): No attachments present...
> W/MmsSmsDatabase( 4543): Executing query: SELECT _id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (thread_id = 2) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (thread_id = 2) ORDER BY date_received DESC)
> W/PushServiceSocket( 4543): Push service URL: https://textsecure-service-staging.whispersystems.org
> W/PushServiceSocket( 4543): Opening URL: https://textsecure-service-staging.whispersystems.org/v1/messages/+491xxxxxx
> W/MmsSmsDatabase( 4543): Executing query: SELECT _id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (thread_id = 2) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (thread_id = 2) ORDER BY date_received DESC)
> D/CellBroadcastReceiver( 3337): onReceive Intent { act=android.intent.action.SERVICE_STATE flg=0x10 cmp=com.android.cellbroadcastreceiver/.CellBroadcastReceiver (has extras) }
> D/CellBroadcastReceiver( 3337): Intent ACTION_SERVICE_STATE_CHANGED
> D/CellBroadcastReceiver( 3337): Service state changed! 0 Full: 0 0 voice home data home MEDIONmobile  26203 MEDIONmobile  26203  UMTS HSPAP CSS not supported -1 -1 RoamInd=-1 DefRoamInd=-1 EmergOnly=false Current state=-1
> D/ConnectivityManager.CallbackHandler( 2145): CM callback handler got msg 524290
> D/ConnectivityManager.CallbackHandler( 2145): CM callback handler got msg 524294
> D/ConnectivityManager.CallbackHandler( 2145): CM callback handler got msg 524295
> D/CellBroadcastConfigService( 3337): enabling emergency cell broadcast channels
> D/CellBroadcastConfigService( 3337): enabled emergency cell broadcast channels
> D/CellBroadcastConfigService( 3337): disabling cell broadcast channel 50
> D/CellBroadcastConfigService( 3337): disabling channels 919-928
> D/CellBroadcastConfigService( 3337): disabling cell broadcast ETWS test messages
> W/PushServiceSocket( 4543): PUT  --  {"destination":"+491xxxxxx","messages":[{"body":"MwohBevrpPekNSo67utNZB7p19pT/6yAdEv1YeqIwIXartESEAEYACKgAXvd40E/q2wph8BgXO1tdeXrOxFjP1PBEsr558rwH72Lsr5S3LkFd+bVNvG+1Zb4vLvUPPNVb09/5GvhtD52pjWoVXG0cGDoL10ncVTLtqcweDWspODAJRsBjWhI3UvCarWn8LUqEtdBjMHi/lDZK9+LjiJHJhc2NPSjDPuEm3OaZU92fQfoUkKyqfjfdSQBVWFoYboTPoutT94043CXoQn2SsZYb145qQ==","content":null,"destinationDeviceId":1,"destinationRegistrationId":3650,"type":1}],"relay":null,"timestamp":1444226429014}
> D/CellBroadcastConfigService( 3337): disabling cell broadcast CMAS test messages
> W/MessageDatabase( 4543): Updating ID: 4 to base type: 2097152
> W/MmsSmsDatabase( 4543): Executing query: SELECT _id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (thread_id = 2) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (thread_id = 2) ORDER BY date_received DESC) LIMIT 1
> W/MessageDatabase( 4543): Updating ID: 4 to base type: 8388608
> W/MmsSmsDatabase( 4543): Executing query: SELECT _id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (thread_id = 2) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (thread_id = 2) ORDER BY date_received DESC)
> W/MmsSmsDatabase( 4543): Executing query: SELECT _id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (thread_id = 2) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (thread_id = 2) ORDER BY date_received DESC) LIMIT 1
> W/MessageDatabase( 4543): Updating ID: 4 to base type: 23
> W/MmsSmsDatabase( 4543): Executing query: SELECT _id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (thread_id = 2) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (thread_id = 2) ORDER BY date_received DESC) LIMIT 1
> W/MmsSmsDatabase( 4543): Executing query: SELECT _id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (thread_id = 2) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (thread_id = 2) ORDER BY date_received DESC)
> W/MmsSmsDatabase( 4543): Executing query: SELECT _id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent AS date_sent, date AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (thread_id = 2) UNION ALL SELECT DISTINCT date AS date_sent, date_received AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (thread_id = 2) ORDER BY date_received DESC)
> ^C

**Comment by xmikos** [comment]
@vuyibiran You are connecting to staging server (https://textsecure-service-staging.whispersystems.org), not production server. To be able to communicate with other TextSecure/Signal users, you have to connect to production server. Build Signal like this:

```
./gradlew assembleProdRelease
```

**Comment by relyt29** [comment]
(or if you're using android-studio, make sure on the last page, after you unlock your keystore, you're selecting production, not staging)

**Comment by vuyibiran** [comment]
Thanks a lot, using the staging server does work. So one more question for clarification:
whispersystems is providing different servers that you use with the websocket-version?

**Comment by xmikos** [comment]
@vuyibiran I don't understand you, you were using _staging_ server before (and it was the reason why you couldn't communicate with other TextSecure/Signal users). If you followed our instructions, you are now using _production_ server.

Both _staging_ and _production_ servers are operated by Open Whisper Systems, but _staging_ server is intended for testing development versions only (it doesn't federate with _production_ server, so you can't communicate with other TextSecure/Signal users while using it).

WebSocket fork is using same servers as official TextSecure/Signal apps.

**Comment by vuyibiran** [comment]
@xmikos, thanks for clarification. Closing this ticket now.
