### ISSUE TITLE
Building fails

### ISSUE THREAD

**Issue by mad-de** [JavaJens/TextSecure#43]
Building fails on ubuntu 15.04; Java: Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Tested with Java 7 with same result.

Output:
:dexProdWebsockets
AGPBI: {"kind":"SIMPLE","text":"Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar ","position":{},"original":"Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar "}
AGPBI: {"kind":"SIMPLE","text":"Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000797c80000, 95420416, 0) failed; error\u003d\u0027Cannot allocate memory\u0027 (errno\u003d12)","position":{},"original":"Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000797c80000, 95420416, 0) failed; error\u003d\u0027Cannot allocate memory\u0027 (errno\u003d12)"}

 FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':dexProdWebsockets'.
  
  > com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-8-oracle/bin/java'' finished with non-zero exit value 1
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2 mins 44.742 secs

**Comment by relyt29** [comment]
I don't 100% know what this is saying but it looks to me like your computer ran out of RAM...?

**Comment by JavaJens** [comment]
Feel free to reopen if this issue persists
