### ISSUE TITLE
Playstore Error

### ISSUE THREAD

**Issue by Knexi** [JavaJens/TextSecure#47]
Hi

I got a problem with the Signal Fork without the Google Play Store.
If i try to register my phone number I get the Error that I have to install the Playstore in order to use this app but shouldn't it work without the google Playstore?

I cant get around this error message. Is there any fix for this?

**Comment by JavaJens** [comment]
Did you make sure that you build the Websocket Version?

**Comment by Knexi** [comment]
I'm using the Fdroid build from Michal Krenek on following repo.
I don't know if hes building the websocket version. Maybe you can tell me.

**Comment by Knexi** [comment]
I'm using the Version from Michal Krenek on following repository: https://eutopia.cz/fdroid/repo/
I didn't know that this could be build without the Websocket. Maybe you can tell me if the version from the Repo above is including the Websocket

**Comment by xmikos** [comment]
@Knexi You have to use builds from my _experimental_ repo. In _main_ repo there are builds of official Signal source code (renamed to LibreSignal), not WebSocket fork. See https://fdroid.eutopia.cz

**Comment by Knexi** [comment]
Thanks now it works
