### ISSUE TITLE
Registration without Google Services installed impossible

### ISSUE THREAD

**Issue by nRaecheR** [JavaJens/TextSecure#49]
I've tried to register my phone number with LibeSignal 3.1.1 on my purely ASOP Android device (CM 12) but it states that the Google Play Services it too old. In fact there is nothing from Google Install, no GAPPS. 

Is there any way to use LibreSignal without Google Services ?

**Comment by bonanza123** [comment]
As some kind of workaround you can maybe use https://github.com/microg/android_packages_apps_GmsCore to temporarily install some fake play services.

**Comment by JavaJens** [comment]
Have you looked at #47 ? Just to make sure.

**Comment by vuyibiran** [comment]
@nRaecheR 

Using the websocket-version 3.3.1. without any google apps/framework. You might have done something wrong during compiling.

**Comment by relyt29** [comment]
Did you check that you specified the websocket build when you compiled in Android-Studio?

**Comment by nRaecheR** [comment]
Yes, sorry, it was my fault, I've installed the regular, non-websocket version...sorry for the noise, now it works without problems.

Thank you all for your help ! Closing issue.
