### ISSUE TITLE
Rename repository to LibreSignal

### ISSUE THREAD

**Issue by SecUpwN** [JavaJens/TextSecure#51]
Hi there @JavaJens, first of all: Huge THANKS for making this possible and for rocking the code without Google spy crap for us privacy geeks! I have found your work while reading the article [Android: Signal ohne Google Cloud Messaging](http://www.kuketz-blog.de/android-signal-ohne-google-cloud-messaging/) on the awesome Kuketz Blog. I am sure that if you would rename your fork, much more people would start to use it and contribute. Please do so and never stop raving for us!

**Comment by xenithorb** [comment]
+1 for this considering this is the name as you can find it build on the eutopia.cz repo. 

Any reason this can't be incorporated into F-droid proper now that it doesn't need GCM stuff? 

Regardless, a name that distinguishes itself is important. Thanks for the hard work @JavaJens

**Comment by JavaJens** [comment]
Hey,
I don't think I want to do this. I still think of this repo as a fork and renaming is only required for distribution. Xmikos does this already with his fork nicely.
I don't want to distinguish this repo from anything, it just is a fork for one feature.

Maybe @xmikos cares to create a Organization that manages his build along with a central place for feature requests, but I don't think I want this fork to divert greatly from upstream.

**Comment by SecUpwN** [comment]
> ..but I don't think I want this fork to divert greatly from upstream.

It does not have to. Please just rename your repository to `https://github.com/JavaJens/LibreSignal`. As a user of `LibreSignal` uodating via F-Droid, I was confused as of the naming. Renaming would do:
1. Repository gets found better by people wanting to contribute to its liberty
2. Users know that it is an "unchained" _fork_ of `Signal` and indeed **not** `TextSecure`

**Comment by schachmat** [comment]
Heyho @SecUpwN,

LibreSignal is neither developed nor deployed by JavaJens, therefore it would be inapropriate to rename this repository (as it is inapropriate for any support questions by people who apparently could not inform themselves in advance). LibreSignal is done by @xmikos, therefore he should actually create his own fork to deal with all those non-websocket-feature-related questions.

**Comment by SecUpwN** [comment]
Thanks for your clarification @schachmat, it helped me a lot. Liebe Grüße von um die Ecke! ;-)
