### ISSUE TITLE
Implement OFFLINE SMS encryption

### ISSUE THREAD

**Issue by SecUpwN** [JavaJens/TextSecure#52]
I know that WhisperSystems out offline SMS encryption from their apps, but maybe you'd be able to re-enable SMS encryption from [SMSSecure](https://github.com/SMSSecure/SMSSecure) within LibreSignal? This for sure would make LibreSignal the ULTIMATE app for encrypted communication and I'm sure others would enjoy an "app for everything".

**Comment by JavaJens** [comment]
Please see my comment in #51: I don't want to implement any new features here.
Maybe you can open an issue with SMSSecure to include the upstream changes?

**Comment by SecUpwN** [comment]
> Maybe you can open an issue with SMSSecure to include the upstream changes?

Likely not. @SMSSecure is focused on pure SMS encryption, but maybe they're so kind to respond here?
