### ISSUE TITLE
update signal 3.6.0

### ISSUE THREAD

**Issue by mvught** [JavaJens/TextSecure#55]
Hello,

first i want to thank you all for making a signal version without the need of GCM.
with the websocket version iam able to use signal on my BB10.

iam wondering if its possible to upgrade signal 3.3.1 to a newer version.
as i dont have any experiance with programming iam depinding on you guys to update te to a newer version.

regards

**Comment by schachmat** [comment]
I started creating a new PR a week ago, but didn't have the time to finish it yet. If someone else is faster, be my guest, you're welcome.

**Comment by schachmat** [comment]
Here you go: #56

**Comment by mvught** [comment]
Thanks ;)
