### ISSUE TITLE
instructions incomplete?

### ISSUE THREAD

**Issue by ThomasWaldmann** [JavaJens/TextSecure#57]
thanks for your efforts in getting signal working without gcm!

Somehow the instructions seem incomplete:

https://github.com/JavaJens/TextSecure/wiki/Building-the-Websockets-reborn-fork

i tried to follow them, but noticed some differences:
- cd ~/.m2/repository/org/whispersystems/textsecure-android/2.8.1

that is 2.8.2 now (minor)
- fixing the sha256 of that textsecure-android.aar in build.gradle was not enough, the build later complained about a wrong hash for textsecure-java (note: -java, not -android), so I applied same procedure to textsecure-java.jar also.
- " You'll probably want "Production" and "WS" (Websocket) for your build options."

Not sure what that means, where do I configure "build options"? I used android studio.

Especially, where do I need to tell it to be a "websockets" build?
- I tried a signed apk build, it worked, but after copying it to my android device and installing it, it said it can not work without google play services (which I do not have installed).

wasn't working without them the whole point of this?

**Comment by ThomasWaldmann** [comment]
Trying right now with android studio "Build signed APK":
"Build type": "websockets"
"Flavors": "prod"

But it still complains about missing google play services when it first starts and I try to register my phone number.

**Comment by ThomasWaldmann** [comment]
One also has to be careful to copy the right apk to the device, the one with websocket support is named "TextSecure-prod-websockets.apk" (not: TextSecure-prod-release.apk)

**Comment by ThomasWaldmann** [comment]
I coud register now. :) No nagging for google play services any more.

**Comment by schachmat** [comment]
@ThomasWaldmann you are right about that missing parts in the instructions, could you update the wiki? If you did that and there are no other open questions, I think you can close the issue.

**Comment by ThomasWaldmann** [comment]
OK, wiki page updated, please check it.

**Comment by schachmat** [comment]
Looks good to me, thanks.
