### ISSUE TITLE
Can read old messages despite no password was entered

### ISSUE THREAD

**Issue by vanitasvitae** [JavaJens/TextSecure#58]
Hi

I searched for this bug upstream but couldn't find it there, so I post it here.
I switched from upstream Signal a few weeks ago (Version 3.7) and now I noticed a unwanted behaviour of the websockets fork that wasn't in upstream.

Sometimes when I get a new message and I double tap on the notification in my phones lockscreen and enter my phones pin, I end up directly in the conversation without having my signal password entered. There I can scroll through older messages, only the message I just got is replaced with a message saying "decryption in progress" (or similar, my signal is german). It happens not often, but still sometimes.
Is this after all an upstream bug? Did this happen to someone else?

**Comment by relyt29** [comment]
Yes this happens to me as well, I thought it was a function of Replicant and not signal - do you have gplay installed? What ROM, OS version are you using?

**Comment by vanitasvitae** [comment]
Im using copperheadOS based on AOSP. My phone (nexus 5) is fully gapps-free :)

**Comment by ton-io** [comment]
happens to me as well on 3.3.1, 3.6.1 and 3.8.1. all used on a Blackberry with BB10 OS. since there is no google play services support on BB10 iam using this websocket version

**Comment by relyt29** [comment]
If anybody with gApps on their device has this problem please chime in here, otherwise I am assuming that this has to do with lack of gApps.

**Comment by ton-io** [comment]
@vanitasvitae are you still having troubles locking signal? Since 3.10.0 it seems to be solved, at least mine is now locked after the time-out and manual locking the app.

**Comment by vanitasvitae** [comment]
I'll check it soon. I recently build the new version and installed it, but than I had two apps with different app ids on my phone (one app had the suffix .dev). Is there a way to keep groups and secret keys while switching app id? My phone is rooted.

**Comment by vanitasvitae** [comment]
I think this is fixed now.
