### ISSUE TITLE
Pull from upstream to get Signal for Chrome

### ISSUE THREAD

**Issue by matlink** [JavaJens/TextSecure#59]
OpenWhisperSystems recently added Signal for chrome, and therefore allows to connect your phone with Signal with it. It does require to bind them with a QRCode, and the menu is not present in the current version on F-Droid. Is that possible to get that compatibility?

**Comment by JavaJens** [comment]
Should not be a problem of code, merely of time...
I'll maybe try in the next days if nobody else comes first. Maybe @schachmat @f41c0r?

**Comment by schachmat** [comment]
@matlink this should already work with the current v3.6.1. At least I can link the chromium extension with this version. Nevertheless, here you go: #61

**Comment by matlink** [comment]
Well, I'm bad at compiling that kind of app, that's why I asked :)
But if it is a problem of time, nevermind, I'll wait, that was just to test the chromium beta Signal. Thanks.
