### ISSUE TITLE
Websocket protocol change

### ISSUE THREAD

**Issue by brumsoel** [JavaJens/TextSecure#6]
When browsing through the commits of a TextSecure websocket command line client. I found this: https://github.com/janimo/textsecure/commit/cb20c559e31cfe95433554fb73dc2d5dd559030c

Apparently, there has been another protocol change with server version 0.27: Message bodies are no longer Base64-encoded.

Server commit: https://github.com/WhisperSystems/TextSecure-Server/commit/41d15b738bacf7096fe195a5efa5c73bafa15cbb

**Comment by JavaJens** [comment]
@brumsoel Could you check if this solves the problem? Then I would merge into master again.

**Comment by JavaJens** [comment]
@brumsoel That was my fault. I rebased onto the current upstream and lost the PushService in the merge conflict. It was re-added now and should work. Would be great if you could check! Thanks.

**Comment by brumsoel** [comment]
Works perfectly now, thank you!
