### ISSUE TITLE
No notification on receiving message

### ISSUE THREAD

**Issue by otr2015** [JavaJens/TextSecure#66]
Hi,

when I send a message from Signal with websocket support to another user who has Signal with GCM installed, the other user doesn't get a notification that he received a message. The second user always has to open his version of Signal to check if there are new messages. When a message is sent from Signal with GCM to Signal with websocket support it is no problem at all.
Does anyone know why there are no notifications?

Thanks.

**Comment by Diapolo** [comment]
Are both installations using the same version? Could also be some notification bug which was fixed recently.

**Comment by otr2015** [comment]
Yes, both contacts are using the latest version 3.8.1 .

**Comment by otr2015** [comment]
I found the solution for this problem.
In the phone with Signal and GCM installed it was only allowed in the phone's settings to receive notifications but not to show them as notifications.
Whispersystems also knows about this problem: http://support.whispersystems.org/hc/en-us/articles/213190487-Why-is-there-a-delay-in-receiving-messages-
Now the notifications are shown on both phones.
