### ISSUE TITLE
MMS Nonfunctional - Websocket version.

### ISSUE THREAD

**Issue by ClubWDW** [JavaJens/TextSecure#74]
I have a Nexus 6 on CM 13...MMS does not work with websocket version.

**Comment by mimi89999** [comment]
Edit:
Actualy MMS doesn't work for me neither. Sorry for the mistake...

Old:
I'm on CM-13 without gapps and MMS work fine for me.

**Comment by mimi89999** [comment]
@ClubWDW Is it related to: https://github.com/WhisperSystems/Signal-Android/issues/5055 ?

**Comment by JavaJens** [comment]
I have neither cm13 nor do I use mms. Maybe you can submit a debug log?

**Comment by JavaJens** [comment]
If this still is an issue, please re-open and post a debug log.
