### ISSUE TITLE
3.10.0

### ISSUE THREAD

**Issue by ton-io** [JavaJens/TextSecure#79]
just compiled 3.10.0 and its installed next to 3.9.1.
and i need to signup again to signal.

**Comment by JavaJens** [comment]
Yes, this is due to a change in the applicationId.
This way the diff to upstream is smaller again and no other changes to the media providers had to be made.

**Comment by schachmat** [comment]
@ton-io you can revert the removal of the `applicationIdSuffix ".dev"` line from `build.gradle`, rebuild and then it should work again replacing your old v3.9.1.

**Comment by ton-io** [comment]
isnt it better to leave the line in there? or do we probably run into problems in the future?
now people have to register again and create new keys, contact will receive messages about identities now being verified and need to be readd to groups.
for me it wont matter much anymore. i just registered again...
but if you guys decide to place it back again, i have the same problem. think about it further, maybe its better to leave it this way :)

**Comment by JavaJens** [comment]
I think its better to remove. First, there was an issue with the MediaProviders, thus we removed it.
Secondly, I don't think this should be such a big deal anyways, as the change is only in affect for people running a dev or websocket build and I think those should only be used by people, well, developing on it.
I don't know what flavor @xmikos distributes, so maybe this is a larger issue than we think, but at first glance I think its best left like it is.
