### ISSUE TITLE
Groups from websocket-user not available for gcm-user

### ISSUE THREAD

**Issue by jensMF** [JavaJens/TextSecure#8]
I started a group and my friend who is using a gcm-client didn't got any massage from that group. With another websocket-client everything worked well…

**Comment by JavaJens** [comment]
I don't see how the group behavior should be influenced by the technology used by the clients.
Could you check if there are any suspicious messages on the client?
Maybe provide a log from each client, if sth. shows up there.

Also make sure that your friend is on the same server as you (i.e. is not using the play version)

**Comment by jensMF** [comment]
Sorry, I don't have access to my friends phone often, so i have to wait and will compare logcats. I'll report back when done. Probably it's a server-side problem. Didn't think about it...
