### ISSUE TITLE
Update F-Droid repository

### ISSUE THREAD

**Issue by otr2015** [JavaJens/TextSecure#86]
@xmikos Could you please update the F-Droid repository with the last update on Signal?
Thanks.

**Comment by sashw** [comment]
I would really appreciate an update of the F-Droid repository as well, @xmikos.
Edit: At least as long as no official LibreSignal fork is distributed via F-Droid itself.

**Comment by xmikos** [comment]
I have just published updates, see https://github.com/xmikos/fdroiddata/issues/11

**Comment by benediktg** [comment]
@xmikos +1

**Comment by mimi89999** [comment]
:+1:

**Comment by sashw** [comment]
@xmikos Thank you for your work! :-)
