### ISSUE TITLE
libtextsecure is now a standalone library - what next?

### ISSUE THREAD

**Issue by pejakm** [JavaJens/TextSecure#9]
After commit https://github.com/WhisperSystems/TextSecure/commit/ed5b3f867997ec2778e032d8753c3a54a5e23c93 libtextsecure is in separate repo. How will this change affect Web Sockets patch?

**Comment by JavaJens** [comment]
It shouldn't have any effect. AFAIK they just moved it to its own repo.
Feel free to report otherwise
