### ISSUE TITLE
Update to 3.16

### ISSUE THREAD

**Issue by Isgar** [JavaJens/TextSecure#91]
Will you continue updating this fork, at least for now?

My websocket-Signal complains it will be outdated in 9 days, so its time to build a new version.

**Comment by infinity0** [comment]
3.16 LibreSignal is available in F-Droid

**Comment by infinity0** [comment]
To clarify, I mean from [this repo](https://eutopia.cz/experimental/fdroid/repo/) not the f-droid official repos.

**Comment by Isgar** [comment]
I don't understand what the deal is with LibreSignal. The README says its abandoned. Is it identical to this repo, i.e. only websockets, or are there further changes? Does it work to just replace my websocket version from here with a newly compiled LibreSignal?

**Comment by mimi89999** [comment]
@Isgar https://github.com/LibreSignal/LibreSignal/issues/37
